#!/bin/sh -e
#
# 2025 J. Bromley (jbromley@gmail.com)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#


os=$(cat "$__global/explorer/os")

case "$os" in
   ubuntu)
   ;;
   *)
      printf "Your operating system (%s) is currently not supported by this type (%s)\n" "$os" "${__type##*/}" >&2
      printf "Please contribute an implementation for it if you can.\n" >&2
      exit 1
   ;;
esac

user="$__object_id"

__install_deb bat_0.25.0_amd64.deb
__install_deb zoxide_0.9.8-1_amd64.deb
__install_deb helix_25.7.1-1_amd64.deb

__install_archive starship \
  --source starship-x86_64-unknown-linux-gnu.tar.gz \
  --user "${user}"

__install_archive lazygit \
  --source lazygit_0.54.2_linux_x86_64.tar.gz \
  --user "${user}"

__install_archive fzf \
  --source fzf-0.65.1-linux_amd64.tar.gz \
  --user "${user}"

__install_yazi "${user}"
