#!/bin/sh -e
#
# 2025 J. Bromley (jbromley@gmail.com)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

user="$__object_id"

cat <<EOF
su - ${user} -c "bash /tmp/atuin-installer.sh > /dev/null 2>&1"
su - ${user} -c "ln -sf /home/${user}/.atuin/bin/atuin /home/${user}/.local/bin"
EOF
