#!/bin/sh -e
#
# 2025 J. Bromley (jbromley@gmail.com)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#


os=$(cat "$__global/explorer/os")

case "$os" in
   ubuntu)
   ;;
   *)
      printf "Your operating system (%s) is currently not supported by this type (%s)\n" "$os" "${__type##*/}" >&2
      printf "Please contribute an implementation for it if you can.\n" >&2
      exit 1
   ;;
esac

user="$__object_id"
script_url="https://sw.kovidgoyal.net/kitty/installer.sh"
desktop_dir="/home/${user}/.local/share/applications"
terminfo_dir="/home/${user}/.terminfo/x"

__directory "${desktop_dir}" \
    --state present \
    --parents \
    --owner "${user}" \
    --group "${user}"

__directory "${terminfo_dir}" \
    --state present \
    --parents \
    --owner "${user}" \
    --group "${user}"

require="__directory/${desktop_dir} __directory/${terminfo_dir}" \
__download /tmp/kitty-installer.sh \
    --url "${script_url}" \
    --onchange "chmod 644 /tmp/kitty-installer.sh"

